### ISSUE TITLE
LXSim Bottom Button 1 and Bottom Button 2

### ISSUE THREAD

**Issue by PhiJu5** [ryanwoodie/XCSoar-LK8000-LXSim-hotkeys#1]
Hello

FYI works great (thanks) but I have a problem with LXSim
Bottom Button 1 and Bottom Button 2 that do no work,
either a keyboard key or a joystick(s) button(s)
(I try severals differents joystick/buttons)
With a mouse click in LXSim bottom 1 or 2 are functional see attached screen.

Regards

[InputBindings]
LXSim_Top_Button_1=1Joy6
LXSim_Top_Button_2=1Joy7
LXSim_Top_Button_3=1Joy13
LXSim_Top_Button_4=1Joy14
LXSim_Bottom_Button_1=é
LXSim_Bottom_Button_2="
LXSim_Bottom_Button_3=1Joy27
LXSim_Bottom_Button_4=1Joy28
LXSim_OK=1Joy29
LXSim_Cancel=1Joy30
![lxsim1](https://github.com/user-attachments/assets/2216e6b0-04a4-4929-bab4-7a949e2e915e)

**Comment by PhiJu5** [comment]
In above screen click bottom 1 or bottom 2 in LXSim gives attach screen.
![lxsim2](https://github.com/user-attachments/assets/6892542d-b5e9-41f9-a05e-35e9fddb409d)

**Comment by ryanwoodie** [comment]
I'll check it when I get a chance tonight! I likely just have the wrong key
mapped, or something. I have my own simpit with very custom AHK, so I don't
actually use this script myself, so testing is pretty limited.

**Comment by PhiJu5** [comment]
I use an AZERTY keyboard, and there is in dynamic XCS hotkey.ahk
"LXSim_Bottom_Button_1": "{q}", "LXSim_Bottom_Button_2": "{w}", "LXSim_Bottom_Button_3": "{e}", "LXSim_Bottom_Button_4": "{r}"
(QWER)

So I changed to
"LXSim_Bottom_Button_1": "{a}", "LXSim_Bottom_Button_2": "{z}"
(AZER)
and it works.

Thanks.

**Comment by PhiJu5** [comment]
![diff](https://github.com/user-attachments/assets/b9919f08-64fd-4127-9b67-f84f3c2b18c1)
 "dynamic XCS hotkey azerty.ahk"

**Comment by ryanwoodie** [comment]
Sorry I had completely forgot to check, but I would've only discovered it
worked OK ;-)

LX_Sim must detect the type of keyboard and change it's hotkeys accordingly.

Thanks for figuring that out.

**Comment by ryanwoodie** [comment]
I've added keyboard detection if you want to test and see if it works with your keyboard.

**Comment by PhiJu5** [comment]
FYI.
Was away. Latest dynamic XCS hotkey.ahk

SetFormat, Integer, H
kbLayout := DllCall("GetKeyboardLayout", "UInt", 0, "UInt")
SetFormat, Integer, D

kbLayout value is 0x40C040C for my PC

so does not trigger the switch, but below does

Switch kbLayout {
    ; French AZERTY
    Case 0x40C0409, 0x40C040C, 0x40C:

**Comment by ryanwoodie** [comment]
Hi you are saying the keyboard switching is, or is not working?
