### ISSUE TITLE
problem with assigning bottom left zoom in and out dials

### ISSUE THREAD

**Issue by Stevemyall** [ryanwoodie/XCSoar-LK8000-LXSim-hotkeys#2]
Hi, Thanks so much for sharing this. Its allowed me to finish my condor button box project to control the LX. All working fine apart from 

a problem with assigning bottom left zoom in and out dials. 

![image](https://github.com/user-attachments/assets/b792e789-60f6-4a07-949e-c247f69cbd9c)

I get this error once I manage to assign for both zoom in and zoom out and LX sim is not picking up the inputs.

![image](https://github.com/user-attachments/assets/e6d1bcd0-5494-4d0b-a2a8-30bd4089c952)

Fortunately there is a work around to assign the zoom in and out controls directly in condor but wondered if this is a bug that's fixable?

Kind Regards

Steve

**Comment by ryanwoodie** [comment]
Hi Steve,
Yes this is likely because you have the same control assigned somewhere. Try to change it, or remove it from the config.ini file directly

**Comment by Stevemyall** [comment]
Hi, Sorry for being dim but where do I find the config.ini file? I'm using the .exe version for info. 
I have noticed that condor assigns button 26 and 27 whilst the hot key app assigns buttons 27 & 28 with the same inputs which aligns with the game controller test tab. Not sure if that's significant?

**Comment by ryanwoodie** [comment]
It will be the same directory the .exe is stored in.

Yes, it's a Condor thing. Condor starts at button 0 vs 1 which is why it is
shifted.

**Comment by Stevemyall** [comment]
Thanks for the reply,

![image](https://github.com/user-attachments/assets/99cbea25-5f61-4245-a59f-b5fa9923e83c)

I have no config.ini, Do you mean the settings.ini? There are no duplicates in there if so.

**Comment by ryanwoodie** [comment]
Yes settings.ini. There won't be duplicates, the errors is because it
doesn't allow duplicates. But you can clear the mapping(s) that you want to
use elsewhere.

**Comment by ryanwoodie** [comment]
It's been update to handle (remove) duplicate assignments now. Give it a try.
